### ISSUE TITLE
#[axum::debug_hander] causes compilation error

### ISSUE THREAD

**Issue by sublipri** [matteopolak/axum-codec#1]
Hi, thanks for your work on this! I'm trying it out in a project.

One issue I ran into was using `[axum::debug_handler]` to troubleshoot something, then being left with another error after I fixed the initial problem. The error seems to occur if it's used on any handler that returns `impl IntoCodecResponse` e.g.:

```rust
error[E0277]: the trait bound `impl IntoCodecResponse: IntoResponse` is not satisfied
  --> examples/basic/src/main.rs:19:18
   |
19 | async fn me() -> impl IntoCodecResponse {
   |                  ^^^^ the trait `IntoResponse` is not implemented for `impl IntoCodecResponse`
   |
   = help: the following other types implement trait `IntoResponse`:
             &'static [u8; N]
             &'static [u8]
             &'static str
             ()
             (R,)
             (Response<()>, R)
             (Response<()>, T1, R)
             (Response<()>, T1, T2, R)
           and 122 others
note: required by a bound in `__axum_macros_check_me_into_response::{closure#0}::check`
  --> examples/basic/src/main.rs:19:18
   |
19 | async fn me() -> impl IntoCodecResponse {
   |                  ^^^^ required by this bound in `check`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `basic` (bin "basic") due to 1 previous error

```

It took me a while to realize that I just needed to remove `debug_handler` to fix the error.

**Comment by matteopolak** [comment]
Hey there, thanks!

I'll submit a new release soon (currently on vacation) with a `debug_handler` macro that checks for the correct trait.

`IntoCodecResponse` unfortunately cannot contain a blanket implementation for `IntoResponse` (would have been ideal).

I'll put a note about this in the docs too :)

**Comment by sublipri** [comment]
Sounds good enjoy your vacation :)

**Comment by matteopolak** [comment]
Added `#[axum_codec::debug_handler]` and `#[axum_codec::debug_middleware]` to version 0.0.13. Feel free to re-open this if there are any related issues!
