### ISSUE TITLE
Consider passing `content_type` by reference

### ISSUE THREAD

**Issue by hqdncw** [matteopolak/axum-codec#6]
Hey, I'm not sure it's necessary to take ownership of `content_type` in the methods listed below. Passing it by reference instead (&ContentType) seems like a more idiomatic approach and avoids unnecessary cloning. Thoughts?

https://github.com/matteopolak/axum-codec/blob/7a3d88989059c2f7be25c5dbf38447f17a1bd3f3/src/response.rs#L12
https://github.com/matteopolak/axum-codec/blob/7a3d88989059c2f7be25c5dbf38447f17a1bd3f3/src/encode.rs#L148
https://github.com/matteopolak/axum-codec/blob/7a3d88989059c2f7be25c5dbf38447f17a1bd3f3/src/decode.rs#L120

See also:
https://rust-unofficial.github.io/patterns/anti_patterns/borrow_clone.html

**Comment by matteopolak** [comment]
Hey, thanks for your concerns! :)

`ContentType` implements `Copy` and is 1 byte, if the signature changed to take a `&ContentType` it would become the size of a usize (4 or 8 bytes most commonly). I don't know if there's a guide I can point to, but the general rule of thumb is to pass by value if the type is smaller/roughly the same as a usize (so bool, u8, u16, ..., u128) - once you get to something like `[u8; 16]` I would probably switch to `&[u8; 16]` depending on the context.

The docs you linked are for `Clone` (which `ContentType` also is, but only so it can implement `Copy`).

Let me know if that answers your questions

**Comment by hqdncw** [comment]
> Hey, thanks for your concerns! :)
> 
> `ContentType` implements `Copy` and is 1 byte, if the signature changed to take a `&ContentType` it would become the size of a usize (4 or 8 bytes most commonly). I don't know if there's a guide I can point to, but the general rule of thumb is to pass by value if the type is smaller/roughly the same as a usize (so bool, u8, u16, ..., u128) - once you get to something like `[u8; 16]` I would probably switch to `&[u8; 16]` depending on the context.
> 
> The docs you linked are for `Clone` (which `ContentType` also is, but only so it can implement `Copy`).
> 
> Let me know if that answers your questions

Yeah, that makes sense. So it's basically about passing by value if the type is small, like a usize or smaller, and by reference if it's larger. Got it, thanks!
